# Generated by Django 4.2.7 on 2023-11-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("prefix", models.CharField(max_length=4)),
                ("number", models.CharField(max_length=4)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
    ]
